version: '3.3'
services:


  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: alevaka/foodgram:latest
    command: >
        bash -c "python manage.py migrate &&
                 python manage.py collectstatic --no-input &&
                 gunicorn foodgram.wsgi:application --bind 0:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3

    ports:
      - "80:80"
    restart: always
    volumes:

      - static_value:/var/html/static/
      - media_value:/var/html/media/

      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

    depends_on:
      - web

  frontend:
    image: alevaka/foodgram-frontend:latest
    volumes:
      - frontend_build:/app/result_build/build/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  frontend_build:
