# Generated by Django 3.2.15 on 2022-09-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershoppingcart',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='usershoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
        migrations.DeleteModel(
            name='UserShoppingCart',
        ),
    ]
